version: 2
updates:
  # 1. GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "aarakke"
    labels:
      - "github-actions"
      - "dependencies"

  # 2. Python packages (using pip)
  - package-ecosystem: "pip"
    directory: "/" # Location of your manifest files
    schedule:
      interval: "daily"
    reviewers:
      - "aarakke"
    labels:
      - "python"
      - "dependencies"
