name: Changelog

on:
  pull_request_target:
    types:
      - opened

jobs:
  create-changelog-entry:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Create changelog entry
        run: |
          echo "${{ github.event.pull_request.title }}" > changelog/${{ github.event.pull_request.number }}.bumped.md

      - name: Commit and push changelog entry
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: "docs(changelog): Add entry for dependency update"
          file_pattern: "changelog/*.md"
