name: Changelog

on:
  pull_request_target:
    types:
      - opened

jobs:
  create-changelog-entry:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4

      - name: Create changelog entry
        run: |
          echo "${{ github.event.pull_request.title }}" > changelog/${{ github.event.pull_request.number }}.bumped.md

      - name: Commit and push changelog entry
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(changelog): Add entry for dependency update"
          file_pattern: "changelog/*.md"
